<?
$name = $this->request->get('name');
$domainId = $this->request->get('domain_id');

$conditions;
if ($domainId) $conditions = "id = $domainId";

$domain = new Domain;
$list = $domain->find([
    'conditions' => $conditions
]);
?>


<div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 medium-centered cell">

        <form accept-charset="UTF-8" action="/alias/add/handler" method="get" data-abide novalidate>
            <h5 class="text-center">Add alias</h5>

            <label>Alias name
                <input type="text" name="name" value="<?= $name ?>" placeholder="name" required pattern="[_\.a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]{2,42}"/>
                <span class="form-error">Mandatory, 2 or more letter</span>
            </label>

            <label>Domain
                <select name="domain_id" required>

                    <? foreach($list as $domain) { ?>
                        <option value="<?= $domain->id ?>"><?= $domain->name ?></option>
                    <? } ?>

                </select >
            </label>

            <label>Destinations list
                <textarea rows="5" name="list" placeholder="one@domain.org,second@domain.org"  required pattern="[_\.a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]{2,42}"></textarea>
                <span class="form-error">Mandatory, 6 or more letter</span>
            </label>

            <div class="text-center">
                <button type="submit" class="button">Accept</button>
                <a class="button" href="/alias/list">Escape</a>
            </div>
        </form>

      </div>
    </div>
</div>
