<?
$id = $this->request->get('id');

$aliases = new Alias;

$alias = $aliases->findFirst($id);
$fcName = $alias->name . '@' . $alias->domain->name;
$result = $alias->delete();
?>


<? if ($result) { ?>
    <div class="callout success">Alias <?= $fcName ?> has been deleted.</div>
<? } ?>

<? if (!$result) { ?>
    <div class="callout alert">Alias <?= $fcName ?> was not deleted.</div>
<? } ?>

<a class="float-left button tiny" href="/alias/list?domain_id=<?= $alias->domainId ?>">
    <i class="fi-arrow-left"></i>
</a>
