<?
$id = $this->request->get('id');

$aliases = new Alias;
$alias = $aliases->findFirst($id);
$fcName = $alias->name . '@' . $alias->domain->name;
?>

<div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 medium-centered cell">

        <form accept-charset="UTF-8" action="/alias/delete/handler" method="get" data-abide novalidate>
            <h5 class="text-center">Delete alias <?= $fcName ?></h5>

            <input type="hidden" name="id" value="<?= $id ?>"/>

            <div class="text-center">
                <button type="submit" class="button">Accept</button>
                <a class="button" href="/alias/list">Escape</a>
            </div>
        </form>

      </div>
    </div>
</div>
