<?
$id = $this->request->get('id');

$suser = new Suser;
$suser = $suser->findFirst($id);
$result = $suser->delete();
?>


<? if ($result) { ?>
    <? $id = $suser->id; ?>
    <div class="callout success">User <?= $suser->name ?> has been deleted.</div>
<? } ?>

<? if (!$result) { ?>
    <div class="callout alert">User <?= $suser->name ?> was not deleted.</div>
<? } ?>

<a class="float-left button tiny" href="/suser/list">
    <i class="fi-arrow-left"></i>
</a>
