<?
$user = new User;

$user->name = $this->request->get('name');
$user->password = $this->request->get('password');
$user->domainId = $this->request->get('domain_id');
$user->gecos = $this->request->get('gecos');

$result = $user->create();
?>


<? if ($result) { ?>
    <? $id = $user->id; ?>
    <div class="callout success">User <?= $name ?> has been added.</div>
<? } ?>


<? if (!$result) { ?>
    <div class="callout alert">User <?= $name ?> was not added.</div>
<? } ?>

<a class="float-left button tiny" href="/user/list?domain_id=<?= $user->domainId ?>">
    <i class="fi-arrow-left"></i>
</a>
