<?
$domainId = $this->request->get('domain_id');

$conditions;
if ($domainId) $conditions = "id = $domainId";

$domain = new Domain;
$list = $domain->find([
    'conditions' => $conditions
]);
?>


<div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 medium-centered cell">

        <form accept-charset="UTF-8" action="/user/add/handler" method="get" data-abide novalidate>
            <h5 class="text-center">Add user</h5>
            <label>Name
                <input type="text" name="name" placeholder="SomeLogin" required pattern="[_\.a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]{2,42}"/>
                <span class="form-error">Mandatory, 2 or more letter</span>
            </label>

            <label>Domain
                <select name="domain_id" required>

                    <? foreach($list as $domain) { ?>
                        <option value="<?= $domain->id ?>"><?= $domain->name ?></option>
                    <? } ?>

                </select >
            </label>

            <label>Description
                <input type="text" name="gecos" placeholder="FirstName LastName" required pattern="[_\.a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]{2,42}"/>
                <span class="form-error">Mandatory, 2 or more letter</span>
            </label>

            <label>Password
                <input type="text" name="password" placeholder="SomePassword" required pattern="[_\.a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]{6,42}"/>
                <span class="form-error">Mandatory, 6 or more letter</span>
            </label>

            <div class="text-center">
                <button type="submit" class="button">Accept</button>
                <a class="button" href="/user/list">Escape</a>
            </div>
        </form>

      </div>
    </div>
</div>
