<?
$id = $this->request->get('id');

$user = new User;
$user = $user->findFirst($id);
$fcName = $user->name.'@'.$user->domain->name;

$result = $user->delete();
?>


<? if ($result) { ?>
    <? $id = $user->id; ?>
    <div class="callout success">User <?= $fcName ?> has been deleted.</div>
<? } ?>

<? if (!$result) { ?>
    <div class="callout alert">User <?= $fcName ?> was not deleted.</div>
<? } ?>

<a class="float-left button tiny" href="/user/list?domain_id=<?= $user->domainId ?>">
    <i class="fi-arrow-left"></i>
</a>
