<?
$id = $this->request->get('id');

$domains = new Domain;

$domain = $domains->findFirst($id);
$name = $domain->name;
?>

<div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 medium-centered cell">

        <form accept-charset="UTF-8" action="/domain/delete/handler" method="get" data-abide novalidate>
            <h5 class="text-center">Delete domain <?= $name ?></h5>

            <input type="hidden" name="id" value="<?= $id ?>"/>

            <div class="text-center">
                <button type="submit" class="button">Accept</button>
                <a class="button" href="/domain/list">Escape</a>
            </div>
        </form>

      </div>
    </div>
</div>
