<?
$id = $this->request->get('id');

$domain = new Domain;
$domain = $domain->findFirst($id);
$name = $domain->name;
?>

<div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 medium-centered cell">

        <form accept-charset="UTF-8" action="/domain/update/handler" method="update" data-abide novalidate>
            <h5 class="text-center">Edit domain <?= $name ?></h5>

            <input type="hidden" name="id" value="<?= $id ?>"/>

            <label>Domain name
                <input type="text" name="name" value="<?= $name ?>" required pattern="[_\.a-zA-Z0-9\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]{5,42}"/>
                <span class="form-error">Mandatory, 5 or more letter</span>
            </label>

            <div class="text-center">
                <button type="submit" class="button">Accept</button>
                <a class="button" href="/domain/list">Escape</a>
            </div>
        </form>

      </div>
    </div>
</div>
