<!doctype html>
<!-- $Id: index.html,v 1.2 2018/05/16 11:12:02 root Exp root $ -->
<!-- $Author: root $ -->

<html class="no-js" lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Phalcon App</title>

        <link rel="stylesheet" href="/icons/foundation-icons.css">
        <link rel="stylesheet" href="/css/foundation-float.min.css">
        <link rel="stylesheet" href="/css/app.css">

        <script src="/js/jquery.min.js"></script>
        <script src="/js/foundation.min.js"></script>
    </head>

    <body>

        <div class="title-bar">
            <button class="menu-icon" type="button" data-toggle="topbar-menu"></button>
            <ul class="dropdown menu" data-dropdown-menu>
                <li class="menu-text">Phalcon App</li>
            </ul>
        </div>

        <div class="row">&nbsp;</div>
        <div class="row">
<!- end of head template ->

<?php echo $this->getContent(); ?>

<!- template tail begin ->
            </div>
        </div>
        <hr/>
        <div class="row">
            <p class="text-center"><a href="https://wiki.unix7.org">Made in Japan</a></small></p>
        </div>
        <script src="/js/app.js"></script>
    </body>
</html>
<!- template tail end ->
<!- EOF ->
